export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const LOAD_DIRECTIONS = 'LOAD_DIRECTIONS';
export const LOAD_EXECUTION_VARIANTS = 'LOAD_EXECUTION_VARIANTS';
export const LOAD_STATUSES = 'LOAD_STATUSES';
export const CLEAR_TASK_OPTIONS = 'CLEAR_TASK_OPTIONS';
