# Generated by Django 3.1.8 on 2021-05-12 18:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('support_mailing_list', models.EmailField(max_length=254, verbose_name='Гпупповой список рассылки группы ТП по направлению')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='ExecutionVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Вариант')),
                ('description', models.TextField(verbose_name='Описание')),
                ('need_engineer', models.BooleanField(default=True, verbose_name='Требуется выделение инженера')),
            ],
            options={
                'verbose_name': 'Особенности исполнения',
                'verbose_name_plural': 'Особенности исполнения',
            },
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('iso_week', models.CharField(blank=True, max_length=7, null=True, verbose_name='Рабочая неделя')),
                ('srv_title', models.CharField(max_length=200, verbose_name='Название запроса')),
                ('description', models.TextField(verbose_name='Состав работ')),
                ('estimated_time', models.FloatField(blank=True, null=True, verbose_name='Ожидаемые трудозатраты')),
                ('srv_number', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Номер должен быть введён в формате SRV123456.', regex='^SRV\\d{6}')], verbose_name='Номер запроса')),
                ('actual_time', models.FloatField(blank=True, null=True, verbose_name='Фактическое время выполнения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('O', 'Open'), ('A', 'Accepted'), ('R', 'Rejected'), ('D', 'Done')], default='O', max_length=1, verbose_name='Статус')),
                ('post_time', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления запроса в БД')),
                ('directions', models.ManyToManyField(related_name='work_tasks', to='work_tasks.Direction', verbose_name='Направления')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_performers', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный инженер')),
                ('execution_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_tasks', to='work_tasks.executionvariant', verbose_name='Особенности исполнения')),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_originators', to=settings.AUTH_USER_MODEL, verbose_name='Оригинатор')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_tasks', to='customers.site', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Рабочая задача',
                'verbose_name_plural': 'Рабочие задачи',
            },
        ),
    ]
