# Generated by Django 3.1.8 on 2021-05-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=100, unique=True, verbose_name='Официальное название организации')),
                ('alternative_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Альтернативное название / торговая марка')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP-статус')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Фактический адрес')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='cities_light.city', verbose_name='Город')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='customers.customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
            },
        ),
    ]
