# Generated by Django 3.1.8 on 2021-05-12 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата выезда/начала работ')),
                ('completion_date', models.DateField(verbose_name='Дата возвращения/окончания работ')),
                ('title', models.CharField(max_length=200, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Описание хода работ')),
                ('results', models.TextField(verbose_name='Итоги работ')),
                ('files', models.TextField(blank=True, null=True, verbose_name='Ссылки на документацию')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания отчёта')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата последней правки отчёта')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tasks', models.ManyToManyField(related_name='reports', to='work_tasks.WorkTask', verbose_name='Запросы')),
            ],
            options={
                'verbose_name': 'Отчёт о работах',
                'verbose_name_plural': 'Отчёты о работах',
            },
        ),
    ]
